# 工作流名称
name: Generate Metrics

# 工作流触发时机, see: https://docs.github.com/zh/actions/using-workflows/triggering-a-workflow
# 触发条件修改为: 当 main 分支有 push 操作 || 每天 0 点
on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"

# 作业, see: https://docs.github.com/zh/actions/using-jobs/using-jobs-in-a-workflow
jobs:
  # 生成统计图, see: https://github.com/lowlighter/metrics
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: metrics-Half-year-calendar
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: assets/metrics.plugin.isocalendar.svg
          token: ${{ github.token }}
          plugin_isocalendar: yes

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: main
          default_author: github_actions
          message: "Generate Contribution Snake"
